name: data_migrator
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  csv: ^5.0.1
  file_picker: ^4.6.1
  flutter_riverpod: ^1.0.3
  vrouter: ^1.2.1
  console_flutter_sdk:
    path: 'appwrite_console_flutter_sdk'
  path_provider: ^2.0.8
  intl: ^0.17.0
  flutter_vector_icons: ^1.0.0
  multi_select_flutter: ^4.0.0
  simple_tooltip: ^1.0.0
  date_time_picker: ^2.1.0
  bitsdojo_window: ^0.1.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/code.tar.gz
    # - assets/insert_bundle_code.tar.gz
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Source Code Pro
      fonts:
        - asset: fonts/source_code_pro/static/SourceCodePro-ExtraLight.ttf
          weight: 200
        - asset: fonts/source_code_pro/static/SourceCodePro-Light.ttf
          weight: 300
        - asset: fonts/source_code_pro/static/SourceCodePro-Regular.ttf
          weight: 400
        - asset: fonts/source_code_pro/static/SourceCodePro-Medium.ttf
          weight: 500
        - asset: fonts/source_code_pro/static/SourceCodePro-SemiBold.ttf
          weight: 600
        - asset: fonts/source_code_pro/static/SourceCodePro-Bold.ttf
          weight: 700
        - asset: fonts/source_code_pro/static/SourceCodePro-ExtraBold.ttf
          weight: 800
        - asset: fonts/source_code_pro/static/SourceCodePro-Black.ttf
          weight: 900
        - asset: fonts/source_code_pro/static/SourceCodePro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/source_code_pro/static/SourceCodePro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/source_code_pro/static/SourceCodePro-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/source_code_pro/static/SourceCodePro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/source_code_pro/static/SourceCodePro-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/source_code_pro/static/SourceCodePro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/source_code_pro/static/SourceCodePro-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/source_code_pro/static/SourceCodePro-BlackItalic.ttf
          weight: 900
          style: italic
    - family: info
      fonts:
        - asset: fonts/libre_baskerville/LibreBaskerville-Italic.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
